import type { RecommendationConfig } from '../types';

export const DEFAULT_RECOMMENDATION_CONFIG: RecommendationConfig = {
  MAX_BATCH_SIZE: 50,
  COMMON_MEMBER_WEIGHT: 100,
  FAVORITE_BONUS: 8,
  HIGH_PRIORITY_BONUS: 12,
  WANT_TO_SING_BONUS: 5,
  PAIR_DIVERSITY_BONUS: 18,
  FAIRNESS_WEIGHT: 8,
  REST_WEIGHT: 3,
  REPEATED_PAIR_PENALTY: 14,
  CONSECUTIVE_SINGER_PENALTY: 20,
  RECENT_HISTORY_PENALTY: 4,
};
